
// Auto-generated file created by react-native-storybook-loader
// Do not edit.
//
// https://github.com/elderfo/react-native-storybook-loader.git

function loadStories() {
  require('../src/components/AppHeader/stories/index.stories');
  require('../src/components/Avatar/stories/index.stories');
  require('../src/components/BookingFooter/stories/index.stories');
  require('../src/components/CarImage/stories/index.stories');
  require('../src/components/CarInfo/stories/index.stories');
  require('../src/components/CardInfo/stories/index.stories');
  require('../src/components/DeleteNbInput/stories/index.stories');
  require('../src/components/DetailsModal/stories/index.stories');
  require('../src/components/DisplayColumn/stories/index.stories');
  require('../src/components/DivisionLine/stories/index.stories');
  require('../src/components/DollarText/stories/index.stories');
  require('../src/components/EmptyList/stories/index.stories');
  require('../src/components/Feedback/stories/index.stories');
  require('../src/components/FilterBar/stories/index.stories');
  require('../src/components/FormScene/stories/index.stories');
  require('../src/components/InfoList/stories/index.stories');
  require('../src/components/InfoListItem/stories/index.stories');
  require('../src/components/LazyImage/stories/index.stories');
  require('../src/components/Loader/stories/index.stories');
  require('../src/components/Mask/stories/index.stories');
  require('../src/components/MemberCard/stories/index.stories');
  require('../src/components/ModalScene/stories/index.stories');
  require('../src/components/ModalSelect/stories/index.stories');
  require('../src/components/MoneyInformation/stories/index.stories');
  require('../src/components/NoticeModal/stories/index.stories');
  require('../src/components/RNToast/stories/index.stories');
  require('../src/components/ReactCalendar/stories/index.stories');
  require('../src/components/RecordDetailList/stories/index.stories');
  require('../src/components/ScrollRuler/stories/index.stories');
  require('../src/components/SeperatorText/stories/index.stories');
  require('../src/components/SideBar/stories/index.stories');
  require('../src/components/Steps/stories/index.stories');
  require('../src/components/TranslateText/stories/index.stories');
  require('../src/components/VerificationCodeTimer/stories/index.stories');
  require('../src/containers/AgentScene/components/AgentBaseInfo/stories/index.stories');
  require('../src/containers/AgentScene/components/AgentEcharts/stories/index.stories');
  require('../src/containers/AgentScene/components/AgentModal/stories/index.stories');
  require('../src/containers/AgentScene/components/CurrentMonthIncome/stories/index.stories');
  require('../src/containers/AgentScene/components/RefIdModal/stories/index.stories');
  require('../src/containers/AgentScene/components/ShareInviteCode/stories/index.stories');
  require('../src/containers/FavouriteCarScene/components/FavouriteCarItem/stories/index.stories');
  require('../src/containers/HomeScene/components/AreaSelectModal/stories/index.stories');
  require('../src/containers/HomeScene/components/CarCard/stories/index.stories');
  require('../src/containers/HomeScene/components/GuideLayer/stories/index.stories');
  require('../src/containers/HomeScene/components/HomeHeader/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/AprList/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/CalendarModal/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/CarFeatures/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/CarInfoCard/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/CarouselImages/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/ConfigurationInfo/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/ConfigurationModal/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/InstallmentPayment/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/Location/stories/index.stories');
  require('../src/containers/InventoryCarScene/components/SimilarVehicles/stories/index.stories');
  require('../src/containers/InventoryScene/components/BrandFilterPart/stories/index.stories');
  require('../src/containers/InventoryScene/components/ColorFilterPart/stories/index.stories');
  require('../src/containers/InventoryScene/components/FilterTitle/stories/index.stories');
  require('../src/containers/InventoryScene/components/OtherFilter/stories/index.stories');
  require('../src/containers/InventoryScene/components/PriceFilter/stories/index.stories');
  require('../src/containers/InventoryScene/components/ProductList/stories/index.stories');
  require('../src/containers/InventoryScene/components/ProductListItem/stories/index.stories');
  require('../src/containers/InventoryScene/components/RangeSlide/stories/index.stories');
  require('../src/containers/InventoryScene/components/SearchHeader/stories/index.stories');
  require('../src/containers/InventoryScene/components/SizeList/stories/index.stories');
  require('../src/containers/InventoryScene/components/SortFilterPart/stories/index.stories');
  require('../src/containers/InventoryScene/components/TopPart/stories/index.stories');
  require('../src/containers/MemberScene/components/MemberCard/stories/index.stories');
  require('../src/containers/MemberScene/components/PrivilegeList/stories/index.stories');
  require('../src/containers/MemberScene/components/PrivilegeModal/stories/index.stories');
  require('../src/containers/PaymentResultScene/stories/index.stories');
  require('../src/containers/SettingScene/components/LogOutModal/stories/index.stories');
  require('../src/containers/SettingScene/components/SettingSceneFeedBack/stories/index.stories');
  require('../src/containers/TripScene/components/TripCard/stories/index.stories');
  require('../src/containers/TripScene/components/TripList/stories/index.stories');
  require('../src/containers/TripScene/components/TripTabs/stories/index.stories');
  require('../src/forms/ChangePasswordCurrentForm/stories/index.stories');
  require('../src/forms/ChangePasswordNewForm/stories/index.stories');
  require('../src/forms/DriverForm/stories/index.stories');
  require('../src/forms/FeedBackForm/stories/index.stories');
  require('../src/forms/LoginForm/stories/index.stories');
  require('../src/forms/PasswordForm/stories/index.stories');
  require('../src/forms/PaymentForm/stories/index.stories');
  require('../src/forms/PhoneVerificationForm/stories/index.stories');
  require('../src/forms/RefIdForm/stories/index.stories');
  require('../src/forms/SimpleProfileForm/stories/index.stories');
  require('../src/forms/WithdrawalForm/stories/index.stories');
  require('../src/forms/formFields/Avatar/stories/index.stories');
  require('../src/forms/formFields/NumberInput/stories/index.stories');
  require('../src/forms/formFields/RadioButton/stories/index.stories');
  require('../src/forms/formFields/SelectInput/stories/index.stories');
  require('../src/forms/formFields/TextInput/stories/index.stories');
  require('../src/forms/formFields/TextareaInput/stories/index.stories');
  
}

const stories = [
  '../src/components/AppHeader/stories/index.stories',
  '../src/components/Avatar/stories/index.stories',
  '../src/components/BookingFooter/stories/index.stories',
  '../src/components/CarImage/stories/index.stories',
  '../src/components/CarInfo/stories/index.stories',
  '../src/components/CardInfo/stories/index.stories',
  '../src/components/DeleteNbInput/stories/index.stories',
  '../src/components/DetailsModal/stories/index.stories',
  '../src/components/DisplayColumn/stories/index.stories',
  '../src/components/DivisionLine/stories/index.stories',
  '../src/components/DollarText/stories/index.stories',
  '../src/components/EmptyList/stories/index.stories',
  '../src/components/Feedback/stories/index.stories',
  '../src/components/FilterBar/stories/index.stories',
  '../src/components/FormScene/stories/index.stories',
  '../src/components/InfoList/stories/index.stories',
  '../src/components/InfoListItem/stories/index.stories',
  '../src/components/LazyImage/stories/index.stories',
  '../src/components/Loader/stories/index.stories',
  '../src/components/Mask/stories/index.stories',
  '../src/components/MemberCard/stories/index.stories',
  '../src/components/ModalScene/stories/index.stories',
  '../src/components/ModalSelect/stories/index.stories',
  '../src/components/MoneyInformation/stories/index.stories',
  '../src/components/NoticeModal/stories/index.stories',
  '../src/components/RNToast/stories/index.stories',
  '../src/components/ReactCalendar/stories/index.stories',
  '../src/components/RecordDetailList/stories/index.stories',
  '../src/components/ScrollRuler/stories/index.stories',
  '../src/components/SeperatorText/stories/index.stories',
  '../src/components/SideBar/stories/index.stories',
  '../src/components/Steps/stories/index.stories',
  '../src/components/TranslateText/stories/index.stories',
  '../src/components/VerificationCodeTimer/stories/index.stories',
  '../src/containers/AgentScene/components/AgentBaseInfo/stories/index.stories',
  '../src/containers/AgentScene/components/AgentEcharts/stories/index.stories',
  '../src/containers/AgentScene/components/AgentModal/stories/index.stories',
  '../src/containers/AgentScene/components/CurrentMonthIncome/stories/index.stories',
  '../src/containers/AgentScene/components/RefIdModal/stories/index.stories',
  '../src/containers/AgentScene/components/ShareInviteCode/stories/index.stories',
  '../src/containers/FavouriteCarScene/components/FavouriteCarItem/stories/index.stories',
  '../src/containers/HomeScene/components/AreaSelectModal/stories/index.stories',
  '../src/containers/HomeScene/components/CarCard/stories/index.stories',
  '../src/containers/HomeScene/components/GuideLayer/stories/index.stories',
  '../src/containers/HomeScene/components/HomeHeader/stories/index.stories',
  '../src/containers/InventoryCarScene/components/AprList/stories/index.stories',
  '../src/containers/InventoryCarScene/components/CalendarModal/stories/index.stories',
  '../src/containers/InventoryCarScene/components/CarFeatures/stories/index.stories',
  '../src/containers/InventoryCarScene/components/CarInfoCard/stories/index.stories',
  '../src/containers/InventoryCarScene/components/CarouselImages/stories/index.stories',
  '../src/containers/InventoryCarScene/components/ConfigurationInfo/stories/index.stories',
  '../src/containers/InventoryCarScene/components/ConfigurationModal/stories/index.stories',
  '../src/containers/InventoryCarScene/components/InstallmentPayment/stories/index.stories',
  '../src/containers/InventoryCarScene/components/Location/stories/index.stories',
  '../src/containers/InventoryCarScene/components/SimilarVehicles/stories/index.stories',
  '../src/containers/InventoryScene/components/BrandFilterPart/stories/index.stories',
  '../src/containers/InventoryScene/components/ColorFilterPart/stories/index.stories',
  '../src/containers/InventoryScene/components/FilterTitle/stories/index.stories',
  '../src/containers/InventoryScene/components/OtherFilter/stories/index.stories',
  '../src/containers/InventoryScene/components/PriceFilter/stories/index.stories',
  '../src/containers/InventoryScene/components/ProductList/stories/index.stories',
  '../src/containers/InventoryScene/components/ProductListItem/stories/index.stories',
  '../src/containers/InventoryScene/components/RangeSlide/stories/index.stories',
  '../src/containers/InventoryScene/components/SearchHeader/stories/index.stories',
  '../src/containers/InventoryScene/components/SizeList/stories/index.stories',
  '../src/containers/InventoryScene/components/SortFilterPart/stories/index.stories',
  '../src/containers/InventoryScene/components/TopPart/stories/index.stories',
  '../src/containers/MemberScene/components/MemberCard/stories/index.stories',
  '../src/containers/MemberScene/components/PrivilegeList/stories/index.stories',
  '../src/containers/MemberScene/components/PrivilegeModal/stories/index.stories',
  '../src/containers/PaymentResultScene/stories/index.stories',
  '../src/containers/SettingScene/components/LogOutModal/stories/index.stories',
  '../src/containers/SettingScene/components/SettingSceneFeedBack/stories/index.stories',
  '../src/containers/TripScene/components/TripCard/stories/index.stories',
  '../src/containers/TripScene/components/TripList/stories/index.stories',
  '../src/containers/TripScene/components/TripTabs/stories/index.stories',
  '../src/forms/ChangePasswordCurrentForm/stories/index.stories',
  '../src/forms/ChangePasswordNewForm/stories/index.stories',
  '../src/forms/DriverForm/stories/index.stories',
  '../src/forms/FeedBackForm/stories/index.stories',
  '../src/forms/LoginForm/stories/index.stories',
  '../src/forms/PasswordForm/stories/index.stories',
  '../src/forms/PaymentForm/stories/index.stories',
  '../src/forms/PhoneVerificationForm/stories/index.stories',
  '../src/forms/RefIdForm/stories/index.stories',
  '../src/forms/SimpleProfileForm/stories/index.stories',
  '../src/forms/WithdrawalForm/stories/index.stories',
  '../src/forms/formFields/Avatar/stories/index.stories',
  '../src/forms/formFields/NumberInput/stories/index.stories',
  '../src/forms/formFields/RadioButton/stories/index.stories',
  '../src/forms/formFields/SelectInput/stories/index.stories',
  '../src/forms/formFields/TextInput/stories/index.stories',
  '../src/forms/formFields/TextareaInput/stories/index.stories',
  
];

module.exports = {
  loadStories,
  stories,
};
